sudo: required

language: shell
#python:
#  - "2.7"
#  - "3.5"
#  - "3.6"
#  - "3.7-dev"

services:
  - docker

before_install:
- docker build -t zabbix .
- docker images
- docker run --name zabbix-appliance -t \
      -p 10051:10051 \
      -p 80:80 \
      -d zabbix
